# Generated by Django 4.2.11 on 2024-09-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gravity_app.usuario')),
                ('direccion', models.CharField(max_length=255)),
            ],
            bases=('gravity_app.usuario',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gravity_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('metodoPago', models.CharField(max_length=50)),
                ('numGuia', models.CharField(max_length=50)),
                ('direccionEntrega', models.CharField(max_length=255)),
                ('totalPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalles', models.ManyToManyField(related_name='pedidos', to='gravity_app.detallepedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gravity_app.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity_app.pedido'),
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProductos', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(to='gravity_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gravity_app.carritocompras'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pedido',
            field=models.ManyToManyField(related_name='clientes', to='gravity_app.pedido'),
        ),
    ]
