# Generated by Django 4.2.11 on 2024-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='totalPagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numGuia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
